### PR TITLE
Use .into() on keys and values

### PR DESCRIPTION
**Pull request by H2CO3**

### CODE REVIEW

**Comment by bluss** [comment]
Hi, thank you!

Please use a description in the PR that explains the thinking behind the change.

This is a wanted feature and I've certainly wanted it -- but I think it would be good to provide it as an **opt in**, somehow, using optional arguments to the macro.

Loose thoughts as examples below:

```rust
let map = hashmap! {
    convert_keys=String::from,
    "a" => 1,
    "b" => 2,
};
```

```rust
let map: HashMap<String, String> = hashmap! {
    convert=Into::into,  // Applies to both keys and values
    "a" => "1",
    "b" => "2",
};
```

Another feature that would be desired would be to specify another capacity than the default via an optional parameter. Since it's a macro we have to see what kind of syntax we want and we can implement.

**Comment by H2CO3** [comment]
Hey,

thanks for the rapid feedback. Fair enough, it makes sense. I think, however, that there could be separate macros for supporting `into()`/`from()` semantics, e.g. `hashmap_from!()`. What do you think?

**Comment by bluss** [comment]
Apparently I had an old WIP lying around for the options thing. I can imagine I didn't want to merge this because it's so ugly.

https://github.com/bluss/maplit/commit/3453d0beefc06e08d8019adede63e33c426e5dc1

**Comment by H2CO3** [comment]
Yep, if I can be honest, I'm not a fan of the LaTeX-style `[options]` syntax either :D

However, there could be a set of fully-featured, customizable macros that take some form of options, and convenience mappers around them. But maybe that is a bit overthinking — a simple map or set literal is usually just used in a read-only manner, so maybe initial capacity is not that important, nor is a custom hasher. If one wants to build a custom map, one will probably need to call multiple stdlib functions/methods anyway. The spirit of these macros is, I think, closer to a quick, not-very-general-but-still-useful-many-times style implementation, similar to map literals in scripting languages.

**Comment by bluss** [comment]
This PR is effectively declined, we don't want to make this change to the existing macros, it will break many current users. See the discussion above for ideas of alternatives (options and other macros).

**Comment by bluss** [comment]
Your input is requested on #15

**Pull request closed without merging**
